### ISSUE TITLE
StopIteration error when training on OfficeHome

### ISSUE THREAD

**Issue by kiranchari** [facebookresearch/DomainBed#147]
I am trying to train on OfficeHome but get this error for some of the trials (I am running 16 hparams x 3 seeds). 

`python -m domainbed.scripts.train --algorithm ERM --data_dir /home/datasets --dataset OfficeHome --holdout_fraction 0.2 --hparams_seed 9 --output_dir output/OfficeHome_ERM/e788b9ef90401eb7d1aab8c0e5408488 --seed 1556291245 --task domain_generalization --test_envs 0 3 --trial_seed 2`

```
Traceback (most recent call last):
  File "/home/users/.conda/envs/domainbed/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/users/.conda/envs/domainbed/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/data/projects/domainbed/scripts/train.py", line 225, in <module>
    for x,y in next(train_minibatches_iterator)]
StopIteration

```

train_minibatches_iterator appears to be empty for some reason. Would appreciate any help to debug this! Thanks.

**Comment by kiranchari** [comment]
Apologies, the issue was due to how I had downloaded the OfficeHome dataset. It was not due to DomainBed.
